name: Train and Save Model

on:
  push:
    paths:
      - trening/trening.py
      - .github/workflows/train.yml
  workflow_dispatch:

jobs:
  train-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r trening/requirements.txt

      - name: Run training script
        run: |
          python trening/trening.py

      - name: Commit model to `modele` branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout --orphan temp-model-branch
          mkdir -p modele
          mv best_model.pkl modele/
          git add trening/best_model.pkl
          git commit -m "Add trained model"

          git push origin --force temp-model-branch:modele
